### ISSUE TITLE
Lyapunov exponents for continuous system incorrect

### ISSUE THREAD

**Issue by RainerEngelken** [Datseris/DynamicalSystems.jl#4]
I tried the Lorenz example:
```
using DynamicalSystems, StaticArrays
ds = Systems.lorenz()
lyapunovs(ds,10^4;dt=1.0, Ttr=10.0)
3-element Array{Float64,1}:
   0.922575
  -1.25806 
 -13.3176
```

but the results are incorrect. The second Lyapunov exponent should be zero because that is the neutral exponent corresponding to perturbations in the direction of time.

**Comment by Datseris** [comment]
Yeap, the method for lyapunov spectra of continuous systems is not yet functional. I have to make it give correct results (It doesn't for some reason). Good to open the issue.

Also, for anybody else that may read this: This package is still in pre-alpha version: the master branch is the development branch, so many things there do not work quite yet. 

The first actual release (with Julia's `Pkg.add()`) will only have well-test and working methods, so when this happens you won't have to worry about things like that.

**Comment by Datseris** [comment]
Finally, after commit 8a28f62432f69c3f175a86223fd178c50c1268f5, I am proud to say that this is working!

**Comment by Datseris** [comment]
It is *terribly* slow however, maybe you can do some magic to make it faster? Although I am quite sure the slowness comes from differential equations solving and the QR...
